#!/bin/bash
cd /home/recruiter-app/
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
NODE_ENV=production pm2 restart index.js --name tc-be --update-env
service httpd restart
